from csv import DictReader
from datetime import datetime
from django.core.management import BaseCommand
from diseases.models import Country
import pandas as pd

ALREADY_LOADED_ERROR_MESSAGE = """
If you need to reload country data from the CSV file,
first delete the db.sqlite3 file to destroy the database.
Then, run `python manage.py migrate` for a new empty
database with tables"""


class Command(BaseCommand):
	# Show this when the user types help
	help = "Loads data from country_names.csv into our Country model"

	def handle(self, *args, **options):
		if Country.objects.exists():
			print('Country data already loaded...exiting.')
			print(ALREADY_LOADED_ERROR_MESSAGE)
			return
		print("Loading data for countries available")
		for row in DictReader(open('./disease/country_names.csv')):
			country = Country()
			country.country_name = row['country_name']
			country.country_code = row['country_code']
			country.save()


	def LoadDiseaseBurden(self, *args, **options):
		if DiseaseBurden.objects.exists():
			print('Disease Burden data already loaded...exiting.')
			print(ALREADY_LOADED_ERROR_MESSAGE)
			return

		print("Loading data for disease burden") 
		

		for row in DictReader(open('./disease/GHE2015_Deaths_2000_country.csv')):
			disease_burden = DiseaseBurden()
			
			disease_burden.Sex = row['Sex']
			disease_burden.GHEcode = row['GHEcode']
			disease_burden.GHEcause = row['GHEcause']
			disease_burden.DiseaseCategory = row['Disease Category'] 
			disease_burden.DiseaseName = row['Disease Name']

			disease_burden.AFG = row['AFG']
			disease_burden.ALB = row['ALB']
			disease_burden.DZA = row['DZA']
			disease_burden.AGO = row['AGO']
			disease_burden.ATG = row['ATG']
			disease_burden.ARG = row['ARG']
			disease_burden.ARM = row['ARM']
			disease_burden.AUS = row['AUS']
			disease_burden.AUT = row['AUT']
			disease_burden.AZE = row['AZE']
			disease_burden.BHS = row['BHS']
			disease_burden.BHR = row['BHR']
			disease_burden.BGD = row['BGD']
			disease_burden.BRB = row['BRB']
			disease_burden.BLR = row['BLR']
			disease_burden.BEL = row['BEL']
			disease_burden.BLZ = row['BLZ']
			disease_burden.BEN = row['BEN']
			disease_burden.BTN = row['BTN']
			disease_burden.BOL = row['BOL']
			disease_burden.BIH = row['BIH']
			disease_burden.BWA = row['BWA']
			disease_burden.BRA = row['BRA']
			disease_burden.BRN = row['BRN']
			disease_burden.BGR = row['BGR']
			disease_burden.BFA = row['BFA']
			disease_burden.BDI = row['BDI']
			disease_burden.KHM = row['KHM']
			disease_burden.CMR = row['CMR']
			disease_burden.CAN = row['CAN']
			disease_burden.CPV = row['CPV']
			disease_burden.CAF = row['CAF']
			disease_burden.TCD = row['TCD']
			disease_burden.CHL = row['CHL']
			disease_burden.CHN = row['CHN']
			disease_burden.COL = row['COL']
			disease_burden.COM = row['COM']
			disease_burden.COG = row['COG']
			disease_burden.CRI = row['CRI']
			disease_burden.CIV = row['CIV']
			disease_burden.HRV = row['HRV']
			disease_burden.CUB = row['CUB']
			disease_burden.CYP = row['CYP']
			disease_burden.CZE = row['CZE']
			disease_burden.PRK = row['PRK']
			disease_burden.COD = row['COD']
			disease_burden.DNK = row['DNK']
			disease_burden.DJI = row['DJI']
			disease_burden.DOM = row['DOM']
			disease_burden.ECU = row['ECU']
			disease_burden.EGY = row['EGY']
			disease_burden.SLV = row['SLV']
			disease_burden.GNQ = row['GNQ']
			disease_burden.ERI = row['ERI']
			disease_burden.EST = row['EST']
			disease_burden.ETH = row['ETH']
			disease_burden.FJI = row['FJI']
			disease_burden.FIN = row['FIN']
			disease_burden.FRA = row['FRA']
			disease_burden.GAB = row['GAB']
			disease_burden.GMB = row['GMB']
			disease_burden.GEO = row['GEO']
			disease_burden.DEU = row['DEU']
			disease_burden.GHA = row['GHA']
			disease_burden.GRC = row['GRC']
			disease_burden.GRD = row['GRD']
			disease_burden.GTM = row['GTM']
			disease_burden.GIN = row['GIN']
			disease_burden.GNB = row['GNB']
			disease_burden.GUY = row['GUY']
			disease_burden.HTI = row['HTI']
			disease_burden.HND = row['HND']
			disease_burden.HUN = row['HUN']
			disease_burden.ISL = row['ISL']
			disease_burden.IND = row['IND']
			disease_burden.IDN = row['IDN']
			disease_burden.IRN = row['IRN']
			disease_burden.IRQ = row['IRQ']
			disease_burden.IRL = row['IRL']
			disease_burden.ISR = row['ISR']
			disease_burden.ITA = row['ITA']
			disease_burden.JAM = row['JAM']
			disease_burden.JPN = row['JPN']
			disease_burden.JOR = row['JOR']
			disease_burden.KAZ = row['KAZ']
			disease_burden.KEN = row['KEN']
			disease_burden.KIR = row['KIR']
			disease_burden.KWT = row['KWT']
			disease_burden.KGZ = row['KGZ']
			disease_burden.LAO = row['LAO']
			disease_burden.LVA = row['LVA']
			disease_burden.LBN = row['LBN']
			disease_burden.LSO = row['LSO']
			disease_burden.LBR = row['LBR']
			disease_burden.LBY = row['LBY']
			disease_burden.LTU = row['LTU']
			disease_burden.LUX = row['LUX']
			disease_burden.MDG = row['MDG']
			disease_burden.MWI = row['MWI']
			disease_burden.MYS = row['MYS']
			disease_burden.MDV = row['MDV']
			disease_burden.MLI = row['MLI']
			disease_burden.MLT = row['MLT']
			disease_burden.MRT = row['MRT']
			disease_burden.MUS = row['MUS']
			disease_burden.MEX = row['MEX']
			disease_burden.FSM = row['FSM']
			disease_burden.MNG = row['MNG']
			disease_burden.MNE = row['MNE']
			disease_burden.MAR = row['MAR']
			disease_burden.MOZ = row['MOZ']
			disease_burden.MMR = row['MMR']
			disease_burden.NAM = row['NAM']
			disease_burden.NPL = row['NPL']
			disease_burden.NLD = row['NLD']
			disease_burden.NZL = row['NZL']
			disease_burden.NIC = row['NIC']
			disease_burden.NER = row['NER']
			disease_burden.NGA = row['NGA']
			disease_burden.NOR = row['NOR']
			disease_burden.OMN = row['OMN']
			disease_burden.PAK = row['PAK']
			disease_burden.PAN = row['PAN']
			disease_burden.PNG = row['PNG']
			disease_burden.PRY = row['PRY']
			disease_burden.PER = row['PER']
			disease_burden.PHL = row['PHL']
			disease_burden.POL = row['POL']
			disease_burden.PRT = row['PRT']
			disease_burden.QAT = row['QAT']
			disease_burden.KOR = row['KOR']
			disease_burden.MDA = row['MDA']
			disease_burden.ROU = row['ROU']
			disease_burden.RUS = row['RUS']
			disease_burden.RWA = row['RWA']
			disease_burden.LCA = row['LCA']
			disease_burden.VCT = row['VCT']
			disease_burden.WSM = row['WSM']
			disease_burden.STP = row['STP']
			disease_burden.SAU = row['SAU']
			disease_burden.SEN = row['SEN']
			disease_burden.SRB = row['SRB']
			disease_burden.SYC = row['SYC']
			disease_burden.SLE = row['SLE']
			disease_burden.SGP = row['SGP']
			disease_burden.SVK = row['SVK']
			disease_burden.SVN = row['SVN']
			disease_burden.SLB = row['SLB']
			disease_burden.SOM = row['SOM']
			disease_burden.ZAF = row['ZAF']
			disease_burden.SSD = row['SSD']
			disease_burden.ESP = row['ESP']
			disease_burden.LKA = row['LKA']
			disease_burden.SDN = row['SDN']
			disease_burden.SUR = row['SUR']
			disease_burden.SWZ = row['SWZ']
			disease_burden.SWE = row['SWE']
			disease_burden.CHE = row['CHE']
			disease_burden.SYR = row['SYR']
			disease_burden.TJK = row['TJK']
			disease_burden.THA = row['THA']
			disease_burden.MKD = row['MKD']
			disease_burden.TLS = row['TLS']
			disease_burden.TGO = row['TGO']
			disease_burden.TON = row['TON']
			disease_burden.TTO = row['TTO']
			disease_burden.TUN = row['TUN']
			disease_burden.TUR = row['TUR']
			disease_burden.TKM = row['TKM']
			disease_burden.UGA = row['UGA']
			disease_burden.UKR = row['UKR']
			disease_burden.ARE = row['ARE']
			disease_burden.GBR = row['GBR']
			disease_burden.TZA = row['TZA']
			disease_burden.USA = row['USA']
			disease_burden.URY = row['URY']
			disease_burden.UZB = row['UZB']
			disease_burden.VUT = row['VUT']
			disease_burden.VEN = row['VEN']
			disease_burden.VNM = row['VNM']
			disease_burden.YEM = row['YEM']
			disease_burden.ZMB = row['ZMB']
			disease_burden.ZWE = row['ZWE']
